//<auto-generated />
namespace Confluent.Avro
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record Confluent.Avro.Person.
    /// </summary>
    [DataContract(Namespace = "Confluent.Avro")]
    public partial class Person
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""Confluent.Avro.Person"",""fields"":[{""name"":""Name"",""type"":""string""},{""name"":""Age"",""type"":""int""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the Name field.
        /// </summary>
        [DataMember]
        public string Name { get; set; }
              
        /// <summary>
        /// Gets or sets the Age field.
        /// </summary>
        [DataMember]
        public int Age { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="Person"/> class.
        /// </summary>
        public Person()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Person"/> class.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="age">The age.</param>
        public Person(string name, int age)
        {
            this.Name = name;
            this.Age = age;
        }
    }
}
